//MOCK DATA IA GENERATED
const initialConfigModel = require('../models/initialConfigModel');
const { insertInitialProducts } = require('../controllers/productController');
const { insertInitialUsers } = require('../controllers/userController');

const mockProducts = [
  {
    title: 'iPhone 12 Pro Max 128GB',
    description: 'Teléfono en perfecto estado, siempre con funda y protector.',
    price: 650,
    images: [],
    category: 'Technology',
    condition: 'Like new',
    brand: 'Apple',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.70379, 40.41678],
      address: {
        country: 'España',
        region: 'Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Sofá de 3 plazas IKEA',
    description: 'Sofá cómodo y amplio, usado pero en buen estado.',
    price: 120,
    images: [],
    category: 'Home and garden',
    condition: 'Good condition',
    brand: 'IKEA',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-0.376288, 39.469907],
      address: {
        country: 'España',
        region: 'Valencia',
        province: 'Valencia',
        city: 'Valencia',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Bicicleta de montaña Rockrider',
    description: 'Bici perfecta para rutas. Frenos hidráulicos, revisada.',
    price: 280,
    images: [],
    category: 'Bicycles',
    condition: 'Good condition',
    brand: 'Rockrider',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-1.130654, 37.98704],
      address: {
        country: 'España',
        region: 'Murcia',
        province: 'Murcia',
        city: 'Murcia',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Lote de libros de ciencia ficción',
    description: '10 libros clásicos de Asimov, Clarke y más.',
    price: 35,
    images: [],
    category: 'Music, books and movies',
    condition: 'Good condition',
    brand: 'Varios',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-5.984459, 37.389092],
      address: {
        country: 'España',
        region: 'Andalucía',
        province: 'Sevilla',
        city: 'Sevilla',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Lavadora Balay 7kg',
    description: 'Funciona perfectamente. La vendemos por mudanza.',
    price: 150,
    images: [],
    category: 'Appliances',
    condition: 'Acceptable',
    brand: 'Balay',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-8.409798, 43.362343],
      address: {
        country: 'España',
        region: 'Galicia',
        province: 'A Coruña',
        city: 'A Coruña',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Zapatillas Nike Air Max 270',
    description: 'Talla 42, usadas 3 veces. Están como nuevas.',
    price: 70,
    images: [],
    category: 'Sport and leisure',
    condition: 'Like new',
    brand: 'Nike',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-4.421265, 36.721274],
      address: {
        country: 'España',
        region: 'Andalucía',
        province: 'Málaga',
        city: 'Málaga',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Silla de oficina ergonómica',
    description:
      'Reposacabezas, respaldo ajustable, muy cómoda para teletrabajo.',
    price: 85,
    images: [],
    category: 'Home and garden',
    condition: 'Good condition',
    brand: 'Herman Miller',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.70379, 40.41678],
      address: {
        country: 'España',
        region: 'Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'PlayStation 4 Slim 500GB + 2 mandos',
    description: 'Perfecto estado, poco uso, con caja original.',
    price: 220,
    images: [],
    category: 'Technology',
    condition: 'In box',
    brand: 'Sony',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-0.889085, 41.648823],
      address: {
        country: 'España',
        region: 'Aragón',
        province: 'Zaragoza',
        city: 'Zaragoza',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Casco moto HJC tamaño M',
    description: 'Con visera solar, cómodo y ligero. Buen estado.',
    price: 90,
    images: [],
    category: 'Vehicle accessories',
    condition: 'Good condition',
    brand: 'HJC',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.70379, 40.41678],
      address: {
        country: 'España',
        region: 'Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Piso en alquiler zona centro',
    description: 'Apartamento de 2 habitaciones, reformado, muy luminoso.',
    price: 750,
    images: [],
    category: 'Real Estate',
    condition: 'Good condition',
    brand: '',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-1.131592, 37.986179],
      address: {
        country: 'España',
        region: 'Murcia',
        province: 'Murcia',
        city: 'Murcia',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Taladro percutor Bosch',
    description: 'Incluye maletín y brocas. Muy potente, ideal para bricolaje.',
    price: 55,
    images: [],
    category: 'Construction',
    condition: 'Good condition',
    brand: 'Bosch',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-1.867, 43.316],
      address: {
        country: 'España',
        region: 'País Vasco',
        province: 'Guipúzcoa',
        city: 'San Sebastián',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Cuna de madera con colchón',
    description: 'Perfecta para bebé, poco uso. Medidas estándar.',
    price: 95,
    images: [],
    category: 'Children and babies',
    condition: 'Like new',
    brand: 'Chicco',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-4.1149, 43.4623],
      address: {
        country: 'España',
        region: 'Cantabria',
        province: 'Cantabria',
        city: 'Santander',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Guitarra eléctrica Fender Stratocaster',
    description:
      'Clásica y en buen estado, ideal para principiantes o intermedios.',
    price: 280,
    images: [],
    category: 'Music, books and movies',
    condition: 'Good condition',
    brand: 'Fender',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-6.3708, 39.4752],
      address: {
        country: 'España',
        region: 'Extremadura',
        province: 'Cáceres',
        city: 'Cáceres',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: "Portátil Lenovo IdeaPad 14''",
    description: '8GB RAM, SSD 256GB, ideal para estudiantes.',
    price: 320,
    images: [],
    category: 'Technology',
    condition: 'Like new',
    brand: 'Lenovo',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-1.644, 42.818],
      address: {
        country: 'España',
        region: 'Navarra',
        province: 'Navarra',
        city: 'Pamplona',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Mesa comedor extensible + 4 sillas',
    description: 'Mesa de roble clara con sillas tapizadas. Buen estado.',
    price: 150,
    images: [],
    category: 'Home and garden',
    condition: 'Good condition',
    brand: 'Conforama',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [2.1701, 41.3874],
      address: {
        country: 'España',
        region: 'Cataluña',
        province: 'Barcelona',
        city: 'Barcelona',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Tablet Samsung Galaxy Tab A7',
    description: 'Con funda magnética y protector de pantalla.',
    price: 140,
    images: [],
    category: 'Technology',
    condition: 'Like new',
    brand: 'Samsung',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.612, 37.179],
      address: {
        country: 'España',
        region: 'Andalucía',
        province: 'Granada',
        city: 'Granada',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Cámara réflex Nikon D3500',
    description: 'Con lente 18-55mm. Ideal para aprender fotografía.',
    price: 310,
    images: [],
    category: 'Technology',
    condition: 'Good condition',
    brand: 'Nikon',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-0.4815, 38.3452],
      address: {
        country: 'España',
        region: 'Valencia',
        province: 'Alicante',
        city: 'Alicante',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Cochecito bebé 3 en 1',
    description: 'Incluye capazo, silla y grupo 0. Color gris oscuro.',
    price: 220,
    images: [],
    category: 'Children and babies',
    condition: 'Good condition',
    brand: 'Jane',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-5.6635, 40.9701],
      address: {
        country: 'España',
        region: 'Castilla y León',
        province: 'Salamanca',
        city: 'Salamanca',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Kit herramientas Black+Decker',
    description: 'Incluye taladro, destornilladores y maletín.',
    price: 85,
    images: [],
    category: 'Construction',
    condition: 'Like new',
    brand: 'Black+Decker',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-2.941, 43.262],
      address: {
        country: 'España',
        region: 'País Vasco',
        province: 'Vizcaya',
        city: 'Bilbao',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Altavoz Bluetooth JBL Flip 5',
    description: 'Gran sonido, resistente al agua. Color azul.',
    price: 60,
    images: [],
    category: 'Technology',
    condition: 'Like new',
    brand: 'JBL',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-6.9272, 38.8794],
      address: {
        country: 'España',
        region: 'Extremadura',
        province: 'Badajoz',
        city: 'Badajoz',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Bicicleta de montaña Trek Marlin 7',
    description: 'Cuadro de aluminio, 21 velocidades, frenos hidráulicos.',
    price: 480,
    images: [],
    category: 'Bicycles',
    condition: 'Good condition',
    brand: 'Trek',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.7038, 40.4168],
      address: {
        country: 'España',
        region: 'Comunidad de Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Sofá cama 3 plazas en tela gris',
    description: 'Apenas usado, cómodo y práctico para espacios pequeños.',
    price: 210,
    images: [],
    category: 'Home and garden',
    condition: 'Like new',
    brand: 'Ikea',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-0.8891, 41.651],
      address: {
        country: 'España',
        region: 'Aragón',
        province: 'Zaragoza',
        city: 'Zaragoza',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: "Monitor gaming ASUS 27'' 144Hz",
    description:
      'Resolución Full HD, tiempos de respuesta bajos, perfecto para gamers.',
    price: 250,
    images: [],
    category: 'Technology',
    condition: 'Good condition',
    brand: 'ASUS',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-4.4214, 36.7213],
      address: {
        country: 'España',
        region: 'Andalucía',
        province: 'Málaga',
        city: 'Málaga',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Equipo de sonido Sony',
    description: 'Con reproductor de CD, radio y altavoces 2.1.',
    price: 90,
    images: [],
    category: 'Music, books and movies',
    condition: 'Good condition',
    brand: 'Sony',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.7038, 40.4168],
      address: {
        country: 'España',
        region: 'Comunidad de Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Smartwatch Fitbit Versa 2',
    description: 'Monitoriza actividad física, sueño y frecuencia cardíaca.',
    price: 110,
    images: [],
    category: 'Technology',
    condition: 'Like new',
    brand: 'Fitbit',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-8.463, 42.8782],
      address: {
        country: 'España',
        region: 'Galicia',
        province: 'A Coruña',
        city: 'A Coruña',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Set de herramientas manuales',
    description: 'Juego completo con llaves, destornilladores y martillo.',
    price: 40,
    images: [],
    category: 'Construction',
    condition: 'Well used',
    brand: 'Stanley',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-5.9845, 37.3891],
      address: {
        country: 'España',
        region: 'Andalucía',
        province: 'Cádiz',
        city: 'Cádiz',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Patinete eléctrico Xiaomi M365',
    description:
      'Batería con buena autonomía, frenos de disco, en perfecto estado.',
    price: 320,
    images: [],
    category: 'Vehicle accessories',
    condition: 'Good condition',
    brand: 'Xiaomi',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.7038, 40.4168],
      address: {
        country: 'España',
        region: 'Comunidad de Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Cámara deportiva GoPro Hero 8',
    description: 'Resistente al agua, con accesorios incluidos.',
    price: 230,
    images: [],
    category: 'Technology',
    condition: 'Good condition',
    brand: 'GoPro',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-1.981, 37.988],
      address: {
        country: 'España',
        region: 'Castilla-La Mancha',
        province: 'Ciudad Real',
        city: 'Ciudad Real',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Reloj de pulsera Seiko automático',
    description: 'Diseño clásico, correa de acero inoxidable.',
    price: 160,
    images: [],
    category: 'Others',
    condition: 'Like new',
    brand: 'Seiko',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.7038, 40.4168],
      address: {
        country: 'España',
        region: 'Comunidad de Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Set de jardinería con herramientas básicas',
    description: 'Ideal para mantenimiento de jardín pequeño o balcón.',
    price: 25,
    images: [],
    category: 'Home and garden',
    condition: 'Good condition',
    brand: 'Fiskars',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-0.627, 39.4699],
      address: {
        country: 'España',
        region: 'Comunidad Valenciana',
        province: 'Valencia',
        city: 'Valencia',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Mesa de comedor extensible',
    description: 'Mesa de madera maciza con capacidad hasta 8 personas.',
    price: 350,
    images: [],
    category: 'Home and garden',
    condition: 'Good condition',
    brand: 'Ikea',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.7038, 40.4168],
      address: {
        country: 'España',
        region: 'Comunidad de Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: "Ordenador portátil HP Pavilion 15''",
    description: 'Intel i5, 8GB RAM, SSD 256GB, pantalla Full HD.',
    price: 480,
    images: [],
    category: 'Technology',
    condition: 'Good condition',
    brand: 'HP',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-0.491, 39.864],
      address: {
        country: 'España',
        region: 'Comunidad Valenciana',
        province: 'Castellón',
        city: 'Castellón',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Camisa hombre marca Zara, talla M',
    description: 'Color azul, algodón, poco uso.',
    price: 15,
    images: [],
    category: 'Others',
    condition: 'Like new',
    brand: 'Zara',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-6.972, 37.382],
      address: {
        country: 'España',
        region: 'Andalucía',
        province: 'Sevilla',
        city: 'Sevilla',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Silla de oficina ergonómica',
    description: 'Con soporte lumbar y reposabrazos ajustables.',
    price: 90,
    images: [],
    category: 'Home and garden',
    condition: 'Good condition',
    brand: 'Herman Miller',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-4.4214, 36.7213],
      address: {
        country: 'España',
        region: 'Andalucía',
        province: 'Málaga',
        city: 'Málaga',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Volante para simulador Logitech G29',
    description: 'Compatible con PC y PS4, con pedales y force feedback.',
    price: 270,
    images: [],
    category: 'Sport and leisure',
    condition: 'Like new',
    brand: 'Logitech',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.7038, 40.4168],
      address: {
        country: 'España',
        region: 'Comunidad de Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Nevera pequeña para oficina',
    description: 'Capacidad 50 litros, eficiente y silenciosa.',
    price: 75,
    images: [],
    category: 'Appliances',
    condition: 'Good condition',
    brand: 'Samsung',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-0.627, 39.4699],
      address: {
        country: 'España',
        region: 'Comunidad Valenciana',
        province: 'Valencia',
        city: 'Valencia',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Cochecito para bebé Chicco',
    description: 'Muy ligero, plegable, poco uso.',
    price: 120,
    images: [],
    category: 'Children and babies',
    condition: 'Like new',
    brand: 'Chicco',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.7038, 40.4168],
      address: {
        country: 'España',
        region: 'Comunidad de Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Guitarra acústica Yamaha FG800',
    description: 'Sonido limpio, tapa sólida, ideal para principiantes.',
    price: 180,
    images: [],
    category: 'Music, books and movies',
    condition: 'Good condition',
    brand: 'Yamaha',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-2.4597, 43.263],
      address: {
        country: 'España',
        region: 'País Vasco',
        province: 'Vizcaya',
        city: 'Bilbao',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Mochila deportiva Nike',
    description: 'Espaciosa y resistente, color negro con logo rojo.',
    price: 40,
    images: [],
    category: 'Sport and leisure',
    condition: 'Good condition',
    brand: 'Nike',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.7038, 40.4168],
      address: {
        country: 'España',
        region: 'Comunidad de Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Taladro inalámbrico Bosch',
    description: 'Batería de larga duración, 2 velocidades.',
    price: 85,
    images: [],
    category: 'Construction',
    condition: 'Good condition',
    brand: 'Bosch',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-0.8891, 41.651],
      address: {
        country: 'España',
        region: 'Aragón',
        province: 'Zaragoza',
        city: 'Zaragoza',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Bicicleta de montaña Trek Marlin 7',
    description:
      'Bicicleta con cuadro de aluminio, 21 velocidades, frenos de disco.',
    price: 600,
    images: [],
    category: 'Bicycles',
    condition: 'Good condition',
    brand: 'Trek',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.7038, 40.4168],
      address: {
        country: 'España',
        region: 'Comunidad de Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: "Televisor Samsung LED 50''",
    description: 'Resolución 4K UHD, Smart TV con acceso a apps y HDR.',
    price: 400,
    images: [],
    category: 'Technology',
    condition: 'Good condition',
    brand: 'Samsung',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-0.3763, 39.4699],
      address: {
        country: 'España',
        region: 'Comunidad Valenciana',
        province: 'Valencia',
        city: 'Valencia',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Set de herramientas manuales Stanley',
    description:
      'Incluye destornilladores, alicates, martillo y llave inglesa.',
    price: 65,
    images: [],
    category: 'Construction',
    condition: 'Good condition',
    brand: 'Stanley',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-8.417, 43.361],
      address: {
        country: 'España',
        region: 'Galicia',
        province: 'Pontevedra',
        city: 'Vigo',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Juguete educativo para bebés',
    description:
      'Bloques de construcción de madera pintados, aptos para niños de 1-3 años.',
    price: 20,
    images: [],
    category: 'Children and babies',
    condition: 'Brand new',
    brand: 'Melissa & Doug',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.7038, 40.4168],
      address: {
        country: 'España',
        region: 'Comunidad de Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Altavoces Bluetooth JBL',
    description: 'Compactos, resistentes al agua, buena calidad de sonido.',
    price: 55,
    images: [],
    category: 'Technology',
    condition: 'Like new',
    brand: 'JBL',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-4.4214, 36.7213],
      address: {
        country: 'España',
        region: 'Andalucía',
        province: 'Málaga',
        city: 'Málaga',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Reloj Casio Vintage',
    description: 'Modelo clásico digital con cronómetro y alarma.',
    price: 35,
    images: [],
    category: 'Others',
    condition: 'Good condition',
    brand: 'Casio',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.7038, 40.4168],
      address: {
        country: 'España',
        region: 'Comunidad de Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Sofá cama de dos plazas',
    description:
      'Tapizado en tela gris, apertura fácil, ideal para espacios pequeños.',
    price: 180,
    images: [],
    category: 'Home and garden',
    condition: 'Good condition',
    brand: 'Conforama',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-0.491, 39.864],
      address: {
        country: 'España',
        region: 'Comunidad Valenciana',
        province: 'Castellón',
        city: 'Castellón',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Consola Nintendo Switch',
    description: 'Incluye consola, dos mandos Joy-Con y estuche de transporte.',
    price: 270,
    images: [],
    category: 'Technology',
    condition: 'Good condition',
    brand: 'Nintendo',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-3.7038, 40.4168],
      address: {
        country: 'España',
        region: 'Comunidad de Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Bicicleta de paseo Decathlon',
    description:
      'Bicicleta urbana con cesta y guardabarros, ideal para ciudad.',
    price: 150,
    images: [],
    category: 'Bicycles',
    condition: 'Good condition',
    brand: 'Btwin',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-0.627, 39.4699],
      address: {
        country: 'España',
        region: 'Comunidad Valenciana',
        province: 'Valencia',
        city: 'Valencia',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
  {
    title: 'Lavadora Bosch 7kg',
    description: 'Programas variados, eficiencia energética A+++.',
    price: 320,
    images: [],
    category: 'Appliances',
    condition: 'Good condition',
    brand: 'Bosch',
    owner: '68763214f441dca9ebbf5369',
    location: {
      type: 'Point',
      coordinates: [-0.8891, 41.651],
      address: {
        country: 'España',
        region: 'Aragón',
        province: 'Zaragoza',
        city: 'Zaragoza',
      },
    },
    status: 'active',
    lastActivatedAt: new Date(),
  },
];

const mockUsers = [
  {
    firstName: 'Alejandro',
    lastName: 'García Serrano',
    profilePictureUrl: '',
    birthDate: new Date('1980-09-16'),
    email: 'aleboy80@gmail.com',
    password: '1234',
    phone: '644644644',
    dni: '12346578Z',
    location: {
      type: 'Point',
      coordinates: [-4.4067, 36.7459],
      address: {
        country: 'España',
        region: 'Andalucía',
        province: 'Málaga-Costa del Sol',
        city: 'Málaga',
      },
    },
  },
  {
    firstName: 'Lucía',
    lastName: 'Martínez',
    profilePictureUrl: '',
    birthDate: new Date('1990-03-15'),
    email: 'lucia.martinez@example.com',
    password: '1234',
    phone: '612345678',
    dni: '12345678A',
    location: {
      type: 'Point',
      coordinates: [-3.7038, 40.4168], // Madrid
      address: {
        country: 'España',
        region: 'Comunidad de Madrid',
        province: 'Madrid',
        city: 'Madrid',
      },
    },
  },
  {
    firstName: 'Carlos',
    lastName: 'Fernández',
    profilePictureUrl: '',
    birthDate: new Date('1985-07-20'),
    email: 'carlos.fernandez@example.com',
    password: '1234',
    phone: '698765432',
    dni: '87654321B',
    location: {
      type: 'Point',
      coordinates: [-0.3763, 39.4699], // Valencia
      address: {
        country: 'España',
        region: 'Comunidad Valenciana',
        province: 'Valencia',
        city: 'Valencia',
      },
    },
  },
  {
    firstName: 'Marta',
    lastName: 'López',
    profilePictureUrl: '',
    birthDate: new Date('1992-11-02'),
    email: 'marta.lopez@example.com',
    password: '1234',
    phone: '690123456',
    dni: '11223344C',
    location: {
      type: 'Point',
      coordinates: [-5.9845, 37.3891], // Sevilla
      address: {
        country: 'España',
        region: 'Andalucía',
        province: 'Sevilla',
        city: 'Sevilla',
      },
    },
  },
  {
    firstName: 'David',
    lastName: 'Gómez',
    profilePictureUrl: '',
    birthDate: new Date('1988-05-10'),
    email: 'david.gomez@example.com',
    password: '1234',
    phone: '611223344',
    dni: '55667788D',
    location: {
      type: 'Point',
      coordinates: [2.1734, 41.3851], // Barcelona
      address: {
        country: 'España',
        region: 'Cataluña',
        province: 'Barcelona',
        city: 'Barcelona',
      },
    },
  },
];

const cleanedProducts = mockProducts.map(({ location, owner, ...rest }) => ({
  ...rest,
  owner: '',
  lastActivatedAt: new Date(),
}));

const createInitialContent = async () => {
  try {
    let config = await initialConfigModel.findOne();
    if (!config) {
      config = new initialConfigModel();
    }
    if (!config.initialUsersInserted) {
      const instUsr = await insertInitialUsers(mockUsers);
      if (instUsr) config.initialUsersInserted = true;
    }
    if (!config.initialProductsInserted) {
      const instPrd = await insertInitialProducts(cleanedProducts);
      if (instPrd) config.initialProductsInserted = true;
    }
    await config.save();
  } catch (error) {
    console.error('Error inserting initial data', error);
  }
};

module.exports = {
  createInitialContent,
};
